# Site settings
title: Klaus Erber online Profil
email: klaus.erber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Es gibt hier viele Informationen zu meiner Person.
  Der Schwerpunkt liegt hierbei auf meiner beruflichen Qualifikation als IT-Fachkraft.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: isi006
github_username: klauserber

# Build settings
markdown: kramdown
